on:
  push:
    branches:
      - main
# name: 🚀 Deploy website on push
# jobs:
#   web-deploy:
#     name: 🎉 Deploy
#     runs-on: ubuntu-latest
#     steps:
#       - name: 🚚 Atualizando o código
#         uses: actions/checkout@v4

#       build:
#       - name: Build
#         runs-on: ubuntu-latest
#         steps:
#         - name: executando comandos na vps
#           uses: appleboy/ssh-action@v1.0.3
#           with:
#             host: ${{ secrets.HOST }}
#             username: ${{ secrets.USERNAME }}
#             password: ${{ secrets.PASSWORD }}
#             port: ${{ secrets.PORT }}
#             script: whoami